### ISSUE TITLE
Missing directory for Excel download?

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/Teaching-IBioIC-Intro-to-Bioinformatics#52]
According to my pencil notes, this example in ``02-sequence_databases/07-uniprot_programming.ipynb`` needs adjusting to ensure the directory exists:

``` python
# Make a query string, and run a remote search at UniProt,
# getting the result as an Excel spreadsheer
query = "Q01844"
result = service.search(query, frmt="xls")

# Write the Excel spreadsheet to file
outfile = os.path.join('output', 'uniprot', 'Q01844.xlsx')
with open(outfile, 'wb') as ofh:
    ofh.write(result)
```

**Comment by widdowquinn** [comment]
Yep - I need to fix that.

**Comment by widdowquinn** [comment]
The fix I was thinking of was to create the directory and put a placeholder `README.md` in there.

My motivation is to show 'good practice' (my version of it, anyway) by having an almost self-explanatory subdirectory name for the output. Placing the output just under `output` isn't as intuitively informative as `output/uniprot` - though even that doesn't avoid the need to keep a good lab notebook.
