### ISSUE TITLE
Tabular vs CSV in BLAST at terminal lesson?

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/Teaching-IBioIC-Intro-to-Bioinformatics#54]
The final exercise in ``02-sequence_databases/02-blast_at_terminal.ipynb`` includes asking the class to run BLASTX and get CSV output (i.e. ``-outfmt 10``), whereas earlier tabular was used (``-outfmt 6``).

Was this deliberate (to get the students to look at the BLAST help again), or and we stick with tabular to make this run slightly quicker?

**Comment by widdowquinn** [comment]
That's an unfortunate copy/paste on my part from the web-based search. We should change that.
